### ISSUE TITLE
Cannot Find Swig Module Error

### ISSUE THREAD

**Issue by ebowers** [eddywashere/generator-ironsmith#1]
Hey there,

Getting the error below, but not sure why. Any suggestions?

Thanks!

```
module.js:338
    throw err;
    ^
Error: Cannot find module 'swig'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/username/Sites/testing-ironsmith/ironsmith.js:15:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by eddywashere** [comment]
@ebowers try running `npm install swig --save`

I think I had that installed globally. I updated the generator to include that. Let me know if that fixes the issue.

**Comment by ebowers** [comment]
@eddywashere That did the trick. Thanks so much!

**Comment by eddywashere** [comment]
Thank you for reporting it!
